package theme

// Theme represents a visual theme for WeChat article formatting
type Theme struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Styles      map[string]string `json:"styles"`
}

// ThemeGroup represents a group of themes
type ThemeGroup struct {
	Label  string  `json:"label"`
	Themes []Theme `json:"themes"`
}

// ClassicThemes returns the classic theme group
func ClassicThemes() []Theme {
	return []Theme{
		{
			ID:          "apple",
			Name:        "Mac",
			Description: "纯净现代的极致留白，适合日常记录的万能首选",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1d1d1f !important; background-color: #ffffff !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #1d1d1f !important;",
				"strong":     "font-weight: 700; color: #000 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #1d1d1f !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #f5f5f7 !important; border-left: 4px solid #0066cc; color: #555 !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f7 !important; color: #0066cc !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f5f5f7 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f5f5f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1d1d1f !important; border: 1px solid #e0e0e0;",
				"td":         "padding: 12px 16px; border: 1px solid #e0e0e0; color: #1d1d1f !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "claude",
			Name:        "Claude",
			Description: "温润的燕麦卡其色底，适合深度长文或文学哲思",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2b2b2b !important; background-color: #f8f6f0 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #b75c3d !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #b75c3d !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2b2b !important;",
				"strong":     "font-weight: 700; color: #b75c3d !important; background-color: rgba(183,92,61,0.08); padding:0 4px; border-radius:4px;",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #b75c3d !important; text-decoration: none; border-bottom: 1px solid #b75c3d; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #2b2b2b !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: rgba(183, 92, 61, 0.04) !important; border-left: 4px solid #b75c3d; color: #555 !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0ece4 !important; color: #b75c3d !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f0ece4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f0ece4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2b2b !important; border: 1px solid #e0ddd6;",
				"td":         "padding: 12px 16px; border: 1px solid #e0ddd6; color: #2b2b2b !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "wechat",
			Name:        "微信公众号原生",
			Description: "原汁原味的官方绿底纹，满足传统阅读习惯的稳妥之选",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;",
				"strong":     "font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;",
				"td":         "padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "media",
			Name:        "NYT",
			Description: "经典米黄色新闻纸，极强的严肃深度报道专业感",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #000000 !important; background-color: #fdfaf6 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; border-bottom: 2px solid #000; padding-bottom:12px;",
				"h2":         "font-size: 26px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #000000 !important;",
				"strong":     "font-weight: 700; color: #000 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #326891 !important; text-decoration: none; border-bottom: 1px solid #326891; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #000000 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #f0ede8 !important; border-left: 4px solid #326891; color: #555 !important; border-radius: 4px; font-style: italic;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0ede8 !important; color: #326891 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f0ede8 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #d5cfc5 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f0ede8 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #000000 !important; border: 1px solid #d5cfc5;",
				"td":         "padding: 12px 16px; border: 1px solid #d5cfc5; color: #000000 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "medium",
			Name:        "Medium",
			Description: "简约柔和的西式博客排版，适合生活志与随笔沉淀",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.85 !important; color: #242424 !important; background-color: #fcfcfc !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 24px 0 !important; line-height: 1.85 !important; color: #242424 !important;",
				"strong":     "font-weight: 700; color: #000 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #1a8917 !important; text-decoration: none; border-bottom: 1px solid #1a8917; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 10px 0; line-height: 1.85 !important; color: #242424 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: transparent !important; border-left: 3px solid #1a8917; color: #555 !important; border-radius: 0; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f2f3f5 !important; color: #1a8917 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f2f3f5 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f2f3f5 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #242424 !important; border: 1px solid #e0e0e0;",
				"td":         "padding: 12px 16px; border: 1px solid #e0e0e0; color: #242424 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "stripe",
			Name:        "Stripe",
			Description: "前沿的硅谷极客商务风，高悬浮感与高亮视觉系",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #425466 !important; background-color: #f6f9fc !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #425466 !important;",
				"strong":     "font-weight: 700; color: #0a2540 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #635bff !important; text-decoration: none; border-bottom: 1px solid #635bff; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #425466 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #eef0ff !important; border-left: 4px solid #635bff; color: #425466 !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f2fe !important; color: #635bff !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f0f2fe !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #e0e0e0 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f0f2fe !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #425466 !important; border: 1px solid #dde0f0;",
				"td":         "padding: 12px 16px; border: 1px solid #dde0f0; color: #425466 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "workspace",
			Name:        "飞书效率",
			Description: "沉稳严谨的深蓝配色，适合职场效率与管理方法论",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1f2329 !important; background-color: #f7f8fa !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px; border-bottom: 2px solid #3370ff; padding-bottom: 8px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #1f2329 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #1f2329 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #1f2329 !important;",
				"strong":     "font-weight: 700; color: #000 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #3370ff !important; text-decoration: none; border-bottom: 1px solid #3370ff; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #1f2329 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #edf1ff !important; border-left: 4px solid #3370ff; color: #555 !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #eef1f8 !important; color: #3370ff !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #eef1f8 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #dee0e3 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #eef1f8 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1f2329 !important; border: 1px solid #dee0e3;",
				"td":         "padding: 12px 16px; border: 1px solid #dee0e3; color: #1f2329 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "linear",
			Name:        "Linear",
			Description: "纯正的暗夜赛博极客风，编程教程与开发日志的终极归宿",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f1f1f2 !important; background-color: #101114 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #f1f1f2 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #f1f1f2 !important;",
				"strong":     "font-weight: 700; color: #fff !important; ",
				"em":         "font-style: italic; color: #bbb !important;",
				"a":          "color: #5e6ad2 !important; text-decoration: none; border-bottom: 1px solid #5e6ad2; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #f1f1f2 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #1a1a1a !important; border-left: 4px solid #5e6ad2; color: #ccc !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #1a1a2e !important; color: #5e6ad2 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #1a1a2e !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #1a1a2e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #f1f1f2 !important; border: 1px solid #333;",
				"td":         "padding: 12px 16px; border: 1px solid #333; color: #f1f1f2 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "retro",
			Name:        "Retro",
			Description: "做旧羊皮纸搭配火漆红，适合人文历史与艺术鉴赏",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #2b2621 !important; background-color: #f4ecd8 !important; background-image: radial-gradient(circle at center, #f4ecd8 0%, #ebdec4 100%); word-wrap: break-word;",
				"h1":         "font-size: 36px; font-weight: 800; color: #2b2621 !important; line-height: 1.2 !important; margin: 38px 0 20px; letter-spacing: -0.02em; font-variant: small-caps;",
				"h2":         "font-size: 26px; font-weight: 700; color: #8c2211 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2621 !important;",
				"strong":     "font-weight: 700; color: #8c2211 !important; ",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #8c2211 !important; text-decoration: none; border-bottom: 1px solid #8c2211; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #2b2621 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #efe5cc !important; border-left: 4px solid #8c2211; color: #555 !important; border-radius: 4px; font-style: italic;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #ede4d0 !important; color: #8c2211 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #ede4d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #d4c9ae !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #ede4d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2621 !important; border: 1px solid #d4c9ae;",
				"td":         "padding: 12px 16px; border: 1px solid #d4c9ae; color: #2b2621 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "bloomberg",
			Name:        "Bloomberg",
			Description: "还原华尔街古老金融终端机，硬派科技代码展示专属",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Courier New\", Courier, monospace; font-size: 16px; line-height: 1.7 !important; color: #15fa52 !important; background-color: #000000 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
				"h2":         "font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #15fa52 !important;",
				"strong":     "font-weight: 700; color: #15fa52 !important; ",
				"em":         "font-style: italic; color: #bbb !important;",
				"a":          "color: #ff8c00 !important; text-decoration: none; border-bottom: 1px solid #ff8c00; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #15fa52 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #0a0a0a !important; border: 1px solid #333; color: #ccc !important; border-radius: 4px; ",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #0a0a0a !important; color: #ff8c00 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #0a0a0a !important; border: 1px solid #333; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #0a0a0a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #15fa52 !important; border: 1px solid #333;",
				"td":         "padding: 12px 16px; border: 1px solid #333; color: #15fa52 !important;",
				"tr":         "border: none;",
			},
		},
	}
}

// ModernThemes returns the modern theme group
func ModernThemes() []Theme {
	return []Theme{
		{
			ID:          "notion",
			Name:        "Notion",
			Description: "极致克制的黑白灰，纯粹信息密度与无干扰写作",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;",
				"h1":         "font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;",
				"p":          "margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;",
				"strong":     "font-weight: 700; color: #37352f !important;",
				"em":         "font-style: italic; color: #37352f !important;",
				"a":          "color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);",
				"ul":         "margin: 4px 0; padding-left: 26px;",
				"ol":         "margin: 4px 0; padding-left: 26px;",
				"li":         "margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;",
				"blockquote": "margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;",
				"pre":        "margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;",
				"hr":         "margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;",
				"table":      "width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;",
				"td":         "padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "github",
			Name:        "GitHub",
			Description: "开发者最熟悉的阅读界面，README 即视感",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;",
				"h2":         "font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;",
				"h3":         "font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;",
				"h4":         "font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;",
				"p":          "margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;",
				"strong":     "font-weight: 600; color: #1f2328 !important;",
				"em":         "font-style: italic; color: #1f2328 !important;",
				"a":          "color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;",
				"blockquote": "margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;",
				"code":       "font-family: \"SF Mono\", Consolas, \"Liberation Mono\", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;",
				"pre":        "margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;",
				"hr":         "margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;",
				"table":      "width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;",
				"td":         "padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "sspai",
			Name:        "少数派",
			Description: "中文数字媒体标杆，经典红色标识与精致排版",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;",
				"h1":         "font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;",
				"h2":         "font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;",
				"h3":         "font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 12px;",
				"h4":         "font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important;",
				"strong":     "font-weight: 700; color: #d71a1b !important;",
				"em":         "font-style: italic; color: #666 !important;",
				"a":          "color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.8 !important; color: #333333 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;",
				"td":         "padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "dracula",
			Name:        "Dracula",
			Description: "暗紫色赛博吸血鬼美学，粉青撞色的视觉冲击",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;",
				"strong":     "font-weight: 700; color: #ffb86c !important;",
				"em":         "font-style: italic; color: #8be9fd !important;",
				"a":          "color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;",
				"td":         "padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "nord",
			Name:        "Nord",
			Description: "北欧极地冰霜蓝，冷静克制的极光美学",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #d8dee9 !important; background-color: #2e3440 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #88c0d0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #81a1c1 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #88c0d0 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #d8dee9 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #d8dee9 !important;",
				"strong":     "font-weight: 700; color: #eceff4 !important;",
				"em":         "font-style: italic; color: #a3be8c !important;",
				"a":          "color: #88c0d0 !important; text-decoration: none; border-bottom: 1px solid #88c0d0; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #d8dee9 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #3b4252 !important; border-left: 4px solid #5e81ac; color: #d8dee9 !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #3b4252 !important; color: #a3be8c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #3b4252 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #4c566a !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #3b4252 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #88c0d0 !important; border: 1px solid #4c566a;",
				"td":         "padding: 12px 16px; border: 1px solid #4c566a; color: #d8dee9 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "sakura",
			Name:        "樱花",
			Description: "柔粉色系日式美学，温柔感性的少女心表达",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a3f4f !important; background-color: #fef7f9 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #c44569 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #c44569 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.75 !important; color: #4a3f4f !important;",
				"strong":     "font-weight: 700; color: #c44569 !important; background-color: rgba(196,69,105,0.06); padding: 0 4px; border-radius: 4px;",
				"em":         "font-style: italic; color: #9b7fa7 !important;",
				"a":          "color: #c44569 !important; text-decoration: none; border-bottom: 1px solid rgba(196,69,105,0.3); padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.75 !important; color: #4a3f4f !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #fceef2 !important; border-left: 4px solid #e8a0b4; color: #6b5570 !important; border-radius: 8px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #fceef2 !important; color: #c44569 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #fceef2 !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #f0d4dd !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #fceef2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a3f4f !important; border: 1px solid #f0d4dd;",
				"td":         "padding: 12px 16px; border: 1px solid #f0d4dd; color: #4a3f4f !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "ocean",
			Name:        "深海",
			Description: "午夜深蓝配珊瑚橘，沉浸式的海洋系叙事感",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #c8d6e5 !important; background-color: #0c2233 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #ff6b6b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #feca57 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #54a0ff !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #c8d6e5 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #c8d6e5 !important;",
				"strong":     "font-weight: 700; color: #feca57 !important;",
				"em":         "font-style: italic; color: #78e0a0 !important;",
				"a":          "color: #ff6b6b !important; text-decoration: none; border-bottom: 1px solid #ff6b6b; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #c8d6e5 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #152d42 !important; border-left: 4px solid #54a0ff; color: #c8d6e5 !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #152d42 !important; color: #ff6b6b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #152d42 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #1e3a52 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #152d42 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #feca57 !important; border: 1px solid #1e3a52;",
				"td":         "padding: 12px 16px; border: 1px solid #1e3a52; color: #c8d6e5 !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "mint",
			Name:        "薄荷",
			Description: "清凉薄荷绿底色，适合生活方式与健康类内容",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2d4a3e !important; background-color: #f0faf5 !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #1a7a5a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #1a7a5a !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #2d4a3e !important;",
				"strong":     "font-weight: 700; color: #1a7a5a !important;",
				"em":         "font-style: italic; color: #5a8a72 !important;",
				"a":          "color: #1a7a5a !important; text-decoration: none; border-bottom: 1px solid rgba(26,122,90,0.3); padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #2d4a3e !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #e0f5ec !important; border-left: 4px solid #1a7a5a; color: #3d5a4e !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #e0f5ec !important; color: #1a7a5a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #e0f5ec !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #c8e6d8 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #e0f5ec !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2d4a3e !important; border: 1px solid #c8e6d8;",
				"td":         "padding: 12px 16px; border: 1px solid #c8e6d8; color: #2d4a3e !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "sunset",
			Name:        "日落",
			Description: "暖琥珀色调的黄昏意境，散文游记与情感表达",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #3d2c1e !important; background-color: #fdf6ee !important; word-wrap: break-word;",
				"h1":         "font-size: 32px; font-weight: 700; color: #c0582a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
				"h2":         "font-size: 26px; font-weight: 600; color: #c0582a !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 21px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 18px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 20px 0 !important; line-height: 1.8 !important; color: #3d2c1e !important;",
				"strong":     "font-weight: 700; color: #c0582a !important;",
				"em":         "font-style: italic; color: #8a6d4b !important;",
				"a":          "color: #c0582a !important; text-decoration: none; border-bottom: 1px solid rgba(192,88,42,0.3); padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.8 !important; color: #3d2c1e !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #f8ead6 !important; border-left: 4px solid #e8a65d; color: #5a4232 !important; border-radius: 4px; font-style: italic;",
				"code":       "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f5e6d0 !important; color: #c0582a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #f5e6d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #e8d4b8 !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
				"th":         "background-color: #f5e6d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d2c1e !important; border: 1px solid #e8d4b8;",
				"td":         "padding: 12px 16px; border: 1px solid #e8d4b8; color: #3d2c1e !important;",
				"tr":         "border: none;",
			},
		},
		{
			ID:          "monokai",
			Name:        "Monokai",
			Description: "经典代码编辑器配色，程序员的终极浪漫",
			Styles: map[string]string{
				"container":  "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #272822 !important; word-wrap: break-word;",
				"h1":         "font-size: 30px; font-weight: 700; color: #f92672 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;",
				"h2":         "font-size: 24px; font-weight: 600; color: #a6e22e !important; line-height: 1.35 !important; margin: 32px 0 16px;",
				"h3":         "font-size: 20px; font-weight: 600; color: #e6db74 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
				"h4":         "font-size: 17px; font-weight: 600; color: #66d9ef !important; line-height: 1.4 !important; margin: 24px 0 12px;",
				"p":          "margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;",
				"strong":     "font-weight: 700; color: #f92672 !important;",
				"em":         "font-style: italic; color: #e6db74 !important;",
				"a":          "color: #66d9ef !important; text-decoration: none; border-bottom: 1px solid #66d9ef; padding-bottom: 1px;",
				"ul":         "margin: 16px 0; padding-left: 28px;",
				"ol":         "margin: 16px 0; padding-left: 28px;",
				"li":         "margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;",
				"blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #3e3d32 !important; border-left: 4px solid #f92672; color: #a6a68a !important; border-radius: 4px;",
				"code":       "font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; padding: 3px 6px; background-color: #3e3d32 !important; color: #a6e22e !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;",
				"pre":        "margin: 24px 0; padding: 20px; background-color: #3e3d32 !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;",
				"hr":         "margin: 36px auto; border: none; height: 1px; background-color: #49483e !important; width: 100%;",
				"img":        "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
				"table":      "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;",
				"th":         "background-color: #3e3d32 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #a6e22e !important; border: 1px solid #49483e;",
				"td":         "padding: 12px 16px; border: 1px solid #49483e; color: #f8f8f2 !important;",
				"tr":         "border: none;",
			},
		},
	}
}
